/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trafego.view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author wesley
 */
public class TabelaEnviarMensagem extends javax.swing.JFrame {

    /**
     * Creates new form TabelaEnviarMensagem
     */
    public TabelaEnviarMensagem() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtPiloto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        botaoEnviar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMensagem = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DIGITE MENSAGEM ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 420, 180, 20);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("FECHAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(790, 10, 100, 50);

        txtPiloto.setBackground(new java.awt.Color(255, 204, 153));
        txtPiloto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPiloto.setForeground(new java.awt.Color(0, 0, 0));
        txtPiloto.setCaretColor(new java.awt.Color(0, 0, 0));
        txtPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPilotoActionPerformed(evt);
            }
        });
        getContentPane().add(txtPiloto);
        txtPiloto.setBounds(360, 410, 390, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PILOTO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 420, 70, 20);

        botaoEnviar.setBackground(new java.awt.Color(0, 0, 0));
        botaoEnviar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoEnviar.setForeground(new java.awt.Color(255, 255, 255));
        botaoEnviar.setText("ENVIAR");
        botaoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoEnviar);
        botaoEnviar.setBounds(770, 510, 110, 50);

        txtMensagem.setBackground(new java.awt.Color(0, 0, 0));
        txtMensagem.setColumns(20);
        txtMensagem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMensagem.setForeground(new java.awt.Color(255, 255, 255));
        txtMensagem.setRows(5);
        txtMensagem.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(txtMensagem);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 450, 750, 110);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/F163D.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPilotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPilotoActionPerformed

    private void botaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEnviarActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/trafegoaereo", "root",
                        "");
                PreparedStatement st = conectado.prepareStatement("insert into mensagemrecebida values(?,?)");
                st.setString(1, txtPiloto.getText());
                st.setString(2, txtMensagem.getText());

                st.executeUpdate();
                JOptionPane.showMessageDialog(null, " MENSAGEM ENVIADA COM SUCESSO ");
                txtPiloto.setText("");
                txtMensagem.setText("");
                txtPiloto.requestFocus();

            } catch (SQLException ex) {
                JOptionPane.showConfirmDialog(null, ex.getMessage());
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showConfirmDialog(null, ex.getMessage());

        }
    }//GEN-LAST:event_botaoEnviarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaEnviarMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaEnviarMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaEnviarMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaEnviarMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaEnviarMensagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEnviar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtMensagem;
    private javax.swing.JTextField txtPiloto;
    // End of variables declaration//GEN-END:variables
}
