/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trafego.view;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import trafego.model.AeronaveDao;
import trafego.model.ClasseAeronave;
import trafego.model.ClasseComandante;
import trafego.model.ClasseComandanteDao;

/**
 *
 * @author wesley
 */
public class TelaComandante extends javax.swing.JFrame {

    /**
     * Creates new form TelaComandante
     */
    public TelaComandante() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtCadastrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtPiloto = new javax.swing.JTextField();
        pesquisarCod_dac = new javax.swing.JTextField();
        txtHoras_voo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIdentificacao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JButton();
        txtControlador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCod_dac = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCopiloto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 51));
        jButton1.setText("FECHAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(780, 0, 100, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 51));
        jLabel6.setText("HORAS_VÔO");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 460, 100, 22);

        txtCadastrar.setBackground(new java.awt.Color(0, 0, 0));
        txtCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCadastrar.setForeground(new java.awt.Color(255, 204, 51));
        txtCadastrar.setText("CADASTRAR PILOTO");
        txtCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(txtCadastrar);
        txtCadastrar.setBounds(20, 530, 200, 27);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 0));
        jLabel7.setText("PILOTO");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 270, 100, 20);

        txtPiloto.setBackground(new java.awt.Color(0, 0, 0));
        txtPiloto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPiloto.setForeground(new java.awt.Color(255, 204, 0));
        txtPiloto.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPilotoActionPerformed(evt);
            }
        });
        txtPiloto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPilotoKeyPressed(evt);
            }
        });
        getContentPane().add(txtPiloto);
        txtPiloto.setBounds(130, 260, 240, 30);

        pesquisarCod_dac.setBackground(new java.awt.Color(0, 0, 0));
        pesquisarCod_dac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pesquisarCod_dac.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(pesquisarCod_dac);
        pesquisarCod_dac.setBounds(530, 530, 320, 30);

        txtHoras_voo.setBackground(new java.awt.Color(0, 0, 0));
        txtHoras_voo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtHoras_voo.setForeground(new java.awt.Color(255, 255, 255));
        txtHoras_voo.setCaretColor(new java.awt.Color(255, 255, 255));
        txtHoras_voo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoras_vooActionPerformed(evt);
            }
        });
        txtHoras_voo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHoras_vooKeyPressed(evt);
            }
        });
        getContentPane().add(txtHoras_voo);
        txtHoras_voo.setBounds(130, 460, 240, 26);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 51));
        jLabel5.setText("IDENTIFICAÇÃO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 420, 110, 22);

        txtIdentificacao.setBackground(new java.awt.Color(0, 0, 0));
        txtIdentificacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtIdentificacao.setForeground(new java.awt.Color(255, 255, 255));
        txtIdentificacao.setCaretColor(new java.awt.Color(255, 255, 255));
        txtIdentificacao.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtIdentificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificacaoActionPerformed(evt);
            }
        });
        txtIdentificacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdentificacaoKeyPressed(evt);
            }
        });
        getContentPane().add(txtIdentificacao);
        txtIdentificacao.setBounds(130, 420, 240, 26);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 51));
        jLabel3.setText("CONTROLADOR");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 350, 110, 22);

        txtPesquisar.setBackground(new java.awt.Color(0, 0, 0));
        txtPesquisar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        txtPesquisar.setText(" PESQUISAR PILOTO");
        txtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(txtPesquisar);
        txtPesquisar.setBounds(290, 530, 210, 30);

        txtControlador.setBackground(new java.awt.Color(0, 0, 0));
        txtControlador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtControlador.setForeground(new java.awt.Color(255, 255, 255));
        txtControlador.setCaretColor(new java.awt.Color(255, 255, 255));
        txtControlador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtControladorActionPerformed(evt);
            }
        });
        txtControlador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtControladorKeyPressed(evt);
            }
        });
        getContentPane().add(txtControlador);
        txtControlador.setBounds(130, 340, 240, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 51));
        jLabel4.setText("COD-DAC");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 390, 70, 22);

        txtCod_dac.setBackground(new java.awt.Color(0, 0, 0));
        txtCod_dac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCod_dac.setForeground(new java.awt.Color(255, 255, 255));
        txtCod_dac.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCod_dac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCod_dacActionPerformed(evt);
            }
        });
        txtCod_dac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCod_dacKeyPressed(evt);
            }
        });
        getContentPane().add(txtCod_dac);
        txtCod_dac.setBounds(130, 380, 240, 26);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("CO-PILOTO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 300, 100, 30);

        txtCopiloto.setBackground(new java.awt.Color(0, 0, 0));
        txtCopiloto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCopiloto.setForeground(new java.awt.Color(255, 255, 255));
        txtCopiloto.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCopiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCopilotoActionPerformed(evt);
            }
        });
        txtCopiloto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCopilotoKeyPressed(evt);
            }
        });
        getContentPane().add(txtCopiloto);
        txtCopiloto.setBounds(130, 300, 240, 26);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/F163D.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 880, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCopilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCopilotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCopilotoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtControladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtControladorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtControladorActionPerformed

    private void txtCod_dacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCod_dacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCod_dacActionPerformed

    private void txtIdentificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificacaoActionPerformed

    private void txtHoras_vooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoras_vooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoras_vooActionPerformed

    private void txtCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadastrarActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/trafegoAereo", "root",
                        "");
                PreparedStatement st = conectado.prepareStatement("insert into comandante values(?,?,?,?,?,?)");
                st.setString(1, txtPiloto.getText());
                st.setString(2, txtCopiloto.getText());
                st.setString(3, txtControlador.getText());
                st.setString(4, txtCod_dac.getText());
                st.setString(5, txtIdentificacao.getText());
                st.setString(6, txtHoras_voo.getText());
                
                st.executeUpdate();
                JOptionPane.showMessageDialog(null, " COMANDANTE INSERIDO NO SISTEMA ");
                
                txtPiloto.setText("");
                txtCopiloto.setText("");
                txtControlador.setText("");
                txtCod_dac.setText("");
                txtIdentificacao.setText("");
                txtHoras_voo.setText("");
                txtPiloto.requestFocus();
                
            } catch (SQLException ex) {
                JOptionPane.showConfirmDialog(null, ex.getMessage());
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showConfirmDialog(null, ex.getMessage());
            
        }
    }//GEN-LAST:event_txtCadastrarActionPerformed

    private void txtPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPilotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPilotoActionPerformed

    private void txtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarActionPerformed
        String codigo;
        codigo = pesquisarCod_dac.getText();
        ClasseComandanteDao comandanteDao = new ClasseComandanteDao();
        boolean status = comandanteDao.conectar();
        if (status == true) {
            ClasseComandante classeComandante = comandanteDao.consultar(codigo);
            if (classeComandante == null) {
                JOptionPane.showConfirmDialog(null, "COMANDANTE NÃO ENCONTRADO NO BANCO DE DADOS ");
            } else {
                txtPiloto.setText(classeComandante.getNome());
                txtCopiloto.setText(classeComandante.getCo_piloto());
                txtControlador.setText(classeComandante.getControladorAeronave());
                txtCod_dac.setText(classeComandante.getCod_dac());
                txtIdentificacao.setText(classeComandante.getIdentificacaolicenca());
                txtHoras_voo.setText(classeComandante.getHoras_voo());
                
            }
            pesquisarCod_dac.setText("");
            comandanteDao.desconectar();
        } else {
            JOptionPane.showMessageDialog(null, "OPS!!!!FALHA NA CONEXÃO COM BANCO DE DADOS ");
        }
    }//GEN-LAST:event_txtPesquisarActionPerformed

    private void txtPilotoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPilotoKeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            txtCopiloto.requestFocus();
        }// TODO add your handling code here:
    }//GEN-LAST:event_txtPilotoKeyPressed

    private void txtCopilotoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCopilotoKeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            txtControlador.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtCopilotoKeyPressed

    private void txtControladorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtControladorKeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            txtCod_dac.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtControladorKeyPressed

    private void txtCod_dacKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCod_dacKeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            txtIdentificacao.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtCod_dacKeyPressed

    private void txtIdentificacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacaoKeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            txtHoras_voo.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificacaoKeyPressed

    private void txtHoras_vooKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoras_vooKeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            txtCadastrar.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoras_vooKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaComandante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaComandante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaComandante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaComandante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaComandante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField pesquisarCod_dac;
    private javax.swing.JButton txtCadastrar;
    private javax.swing.JTextField txtCod_dac;
    private javax.swing.JTextField txtControlador;
    private javax.swing.JTextField txtCopiloto;
    private javax.swing.JTextField txtHoras_voo;
    private javax.swing.JTextField txtIdentificacao;
    private javax.swing.JButton txtPesquisar;
    private javax.swing.JTextField txtPiloto;
    // End of variables declaration//GEN-END:variables
}
