/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trafego.view;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import trafego.model.AeronaveDao;
import trafego.model.ClasseAeronave;
import trafego.model.ClasseClimaTempo;
import trafego.model.ClimaTempoDao;

/**
 *
 * @author wesley
 */
public class TelaClimaTempo extends javax.swing.JFrame {

    /**
     * Creates new form TelaClimaTempo
     */
    public TelaClimaTempo() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        txtPesquisa = new javax.swing.JTextField();
        txtLocalizacao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtVento = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txtRegistrar = new javax.swing.JButton();
        txtPressao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtUmidade = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtTemperatura = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSensacao = new javax.swing.JTextField();
        txtNuvens = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NUVENS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 330, 70, 20);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(51, 255, 204));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setText("DIGITE LOCALIZAÇÃO");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(410, 530, 160, 26);

        txtPesquisa.setBackground(new java.awt.Color(51, 255, 204));
        txtPesquisa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPesquisa.setForeground(new java.awt.Color(0, 0, 0));
        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(txtPesquisa);
        txtPesquisa.setBounds(370, 560, 240, 40);

        txtLocalizacao.setBackground(new java.awt.Color(51, 255, 204));
        txtLocalizacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtLocalizacao.setForeground(new java.awt.Color(0, 0, 0));
        txtLocalizacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLocalizacaoKeyPressed(evt);
            }
        });
        getContentPane().add(txtLocalizacao);
        txtLocalizacao.setBounds(160, 282, 170, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("LOCALIZAÇÃO");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 290, 120, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PRESSÃO ATM");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 480, 130, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("VENTO");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 520, 130, 20);

        txtVento.setBackground(new java.awt.Color(51, 255, 204));
        txtVento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtVento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtVentoKeyPressed(evt);
            }
        });
        getContentPane().add(txtVento);
        txtVento.setBounds(160, 520, 170, 26);

        jButton2.setBackground(new java.awt.Color(51, 255, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("SAIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(770, 0, 90, 40);

        txtRegistrar.setBackground(new java.awt.Color(102, 255, 204));
        txtRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        txtRegistrar.setText("REGISTRAR CLIMA");
        txtRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(txtRegistrar);
        txtRegistrar.setBounds(10, 560, 170, 40);

        txtPressao.setBackground(new java.awt.Color(51, 255, 204));
        txtPressao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPressao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPressaoKeyPressed(evt);
            }
        });
        getContentPane().add(txtPressao);
        txtPressao.setBounds(160, 482, 170, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("UMIDADE AR");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 450, 130, 20);

        txtUmidade.setBackground(new java.awt.Color(51, 255, 204));
        txtUmidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtUmidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUmidadeKeyPressed(evt);
            }
        });
        getContentPane().add(txtUmidade);
        txtUmidade.setBounds(160, 442, 170, 30);

        jButton3.setBackground(new java.awt.Color(51, 255, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("PESQUISAR CLIMA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(620, 560, 170, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TEMPERATURA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 370, 120, 20);

        txtTemperatura.setBackground(new java.awt.Color(0, 255, 204));
        txtTemperatura.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTemperatura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTemperaturaKeyPressed(evt);
            }
        });
        getContentPane().add(txtTemperatura);
        txtTemperatura.setBounds(160, 366, 170, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SENSAÇÃO TÉRMICA");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 410, 140, 20);

        txtSensacao.setBackground(new java.awt.Color(51, 255, 204));
        txtSensacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSensacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSensacaoKeyPressed(evt);
            }
        });
        getContentPane().add(txtSensacao);
        txtSensacao.setBounds(160, 410, 170, 26);

        txtNuvens.setBackground(new java.awt.Color(51, 255, 204));
        txtNuvens.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNuvens.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNuvensKeyPressed(evt);
            }
        });
        getContentPane().add(txtNuvens);
        txtNuvens.setBounds(160, 330, 170, 26);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/climatempo_resized.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 860, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistrarActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/trafegoAereo", "root",
                        "");
                PreparedStatement st = conectado.prepareStatement("insert into climatempo values(?,?,?,?,?,?,?)");
                st.setString(1, txtLocalizacao.getText());
                st.setString(2, txtNuvens.getText());
                st.setString(3, txtTemperatura.getText());
                st.setString(4, txtSensacao.getText());
                st.setString(5, txtUmidade.getText());
                st.setString(6, txtPressao.getText());
                st.setString(7, txtVento.getText());
                
                st.executeUpdate();
                JOptionPane.showMessageDialog(null, " CLIMATEMPO INSERIDO NO SISTEMA ");
                
                txtLocalizacao.setText("");
                txtNuvens.setText("");
                txtTemperatura.setText("");
                txtSensacao.setText("");
                txtUmidade.setText("");
                txtPressao.setText("");
                txtVento.setText("");
                txtLocalizacao.requestFocus();
                
            } catch (SQLException ex) {
                JOptionPane.showConfirmDialog(null, ex.getMessage());
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showConfirmDialog(null, ex.getMessage());
            
        }
    }//GEN-LAST:event_txtRegistrarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String codigo;
        codigo = txtPesquisa.getText();
        ClimaTempoDao clima = new ClimaTempoDao();
        boolean status = clima.conectar();
        if (status == true) {
            ClasseClimaTempo classeClimaTempo = clima.consultar(codigo);
            if (classeClimaTempo == null) {
                JOptionPane.showConfirmDialog(null, "LOCALIZAÇÃO NÃO ENCONTRADA NO SISTEMA  ");
            } else {
                txtNuvens.setText(classeClimaTempo.getNuvens());
                txtTemperatura.setText(classeClimaTempo.getTemperatura());
                txtSensacao.setText(classeClimaTempo.getSensacao());
                txtUmidade.setText(classeClimaTempo.getUmidadeAr());
                txtPressao.setText(classeClimaTempo.getPressao());
                txtVento.setText(classeClimaTempo.getVento());
                
            }
            txtPesquisa.setText("");
            clima.desconectar();
        } else {
            JOptionPane.showMessageDialog(null, "OPS!!!!FALHA NA CONEXÃO COM BANCO DE DADOS ");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void txtLocalizacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLocalizacaoKeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            txtNuvens.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocalizacaoKeyPressed

    private void txtNuvensKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNuvensKeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            txtTemperatura.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuvensKeyPressed

    private void txtTemperaturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTemperaturaKeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            txtSensacao.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemperaturaKeyPressed

    private void txtSensacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSensacaoKeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            txtUmidade.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtSensacaoKeyPressed

    private void txtUmidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUmidadeKeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            txtPressao.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtUmidadeKeyPressed

    private void txtPressaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPressaoKeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            txtVento.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtPressaoKeyPressed

    private void txtVentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVentoKeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            txtRegistrar.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtVentoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaClimaTempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaClimaTempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaClimaTempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaClimaTempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaClimaTempo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtLocalizacao;
    private javax.swing.JTextField txtNuvens;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtPressao;
    private javax.swing.JButton txtRegistrar;
    private javax.swing.JTextField txtSensacao;
    private javax.swing.JTextField txtTemperatura;
    private javax.swing.JTextField txtUmidade;
    private javax.swing.JTextField txtVento;
    // End of variables declaration//GEN-END:variables
}
