/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trafego.view;

import java.awt.event.KeyEvent;

/**
 *
 * @author wesley
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
         setExtendedState(MAXIMIZED_BOTH);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoLigar = new javax.swing.JButton();
        botaoDesligar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        botaoLigar.setBackground(new java.awt.Color(71, 162, 178));
        botaoLigar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoLigar.setForeground(new java.awt.Color(0, 0, 51));
        botaoLigar.setText("LIGAR SISTEMA ");
        botaoLigar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLigarActionPerformed(evt);
            }
        });
        botaoLigar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoLigarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                botaoLigarKeyReleased(evt);
            }
        });
        getContentPane().add(botaoLigar);
        botaoLigar.setBounds(0, 0, 190, 50);

        botaoDesligar.setBackground(new java.awt.Color(255, 153, 204));
        botaoDesligar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoDesligar.setForeground(new java.awt.Color(0, 0, 102));
        botaoDesligar.setText("DESLIGAR SISTEMA ");
        botaoDesligar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDesligarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoDesligar);
        botaoDesligar.setBounds(10, 580, 180, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/TORREC0NTROLE.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 960, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoLigarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLigarActionPerformed
        TelaLogin tela = new TelaLogin();
        tela.setVisible(rootPaneCheckingEnabled);
        this.dispose();
        tela.setLocationRelativeTo(null);
    }//GEN-LAST:event_botaoLigarActionPerformed

    private void botaoLigarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoLigarKeyPressed
          TelaLogin tela=new TelaLogin();
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            tela.requestFocus();
        }
    }//GEN-LAST:event_botaoLigarKeyPressed

    private void botaoDesligarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDesligarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botaoDesligarActionPerformed

    private void botaoLigarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoLigarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoLigarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoDesligar;
    private javax.swing.JButton botaoLigar;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
