/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trafego.view;

import java.awt.event.KeyEvent;
import trafego.model.ClasseTocarSom;

/**
 *
 * @author wesley
 */
public class TelaMenu extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenu
     */
    public TelaMenu() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoDesligar = new javax.swing.JButton();
        botaoSonoro = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtMensagem = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        botaoClimaTempo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        botaoAeronave = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        botaoComandante = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        botaoDesligar.setBackground(new java.awt.Color(0, 0, 0));
        botaoDesligar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoDesligar.setForeground(new java.awt.Color(255, 255, 255));
        botaoDesligar.setText("DESLIGAR");
        botaoDesligar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDesligarActionPerformed(evt);
            }
        });
        botaoDesligar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoDesligarKeyPressed(evt);
            }
        });
        getContentPane().add(botaoDesligar);
        botaoDesligar.setBounds(840, 520, 150, 40);

        botaoSonoro.setBackground(new java.awt.Color(0, 0, 0));
        botaoSonoro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoSonoro.setForeground(new java.awt.Color(255, 255, 255));
        botaoSonoro.setText("ALERTA SONORO");
        botaoSonoro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSonoroActionPerformed(evt);
            }
        });
        botaoSonoro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoSonoroKeyPressed(evt);
            }
        });
        getContentPane().add(botaoSonoro);
        botaoSonoro.setBounds(0, 540, 290, 30);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensMenu/RADAR6.png"))); // NOI18N
        jLabel8.setText("ALERTA SONORO");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 430, 290, 110);

        txtMensagem.setBackground(new java.awt.Color(0, 0, 0));
        txtMensagem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMensagem.setForeground(new java.awt.Color(255, 255, 255));
        txtMensagem.setText("ENVIAR MENSAGEMS ");
        txtMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMensagemActionPerformed(evt);
            }
        });
        txtMensagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMensagemKeyPressed(evt);
            }
        });
        getContentPane().add(txtMensagem);
        txtMensagem.setBounds(0, 400, 290, 27);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensMenu/radar2.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 330, 290, 80);

        botaoClimaTempo.setBackground(new java.awt.Color(0, 0, 0));
        botaoClimaTempo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoClimaTempo.setForeground(new java.awt.Color(255, 255, 255));
        botaoClimaTempo.setText("CLIMATEMPO");
        botaoClimaTempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClimaTempoActionPerformed(evt);
            }
        });
        botaoClimaTempo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoClimaTempoKeyPressed(evt);
            }
        });
        getContentPane().add(botaoClimaTempo);
        botaoClimaTempo.setBounds(0, 300, 290, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensMenu/radarClima.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 240, 290, 90);

        botaoAeronave.setBackground(new java.awt.Color(0, 0, 0));
        botaoAeronave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoAeronave.setForeground(new java.awt.Color(255, 255, 255));
        botaoAeronave.setText(" AERONAVE");
        botaoAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAeronaveActionPerformed(evt);
            }
        });
        botaoAeronave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoAeronaveKeyPressed(evt);
            }
        });
        getContentPane().add(botaoAeronave);
        botaoAeronave.setBounds(0, 210, 290, 27);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensMenu/radar1.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 130, 290, 110);

        botaoComandante.setBackground(new java.awt.Color(0, 0, 0));
        botaoComandante.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoComandante.setForeground(new java.awt.Color(255, 255, 255));
        botaoComandante.setText("COMANDANTE");
        botaoComandante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoComandanteActionPerformed(evt);
            }
        });
        botaoComandante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoComandanteKeyPressed(evt);
            }
        });
        getContentPane().add(botaoComandante);
        botaoComandante.setBounds(0, 100, 290, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensMenu/f16.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 290, 130);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/abstrato-da-tecnologia-futurista-tela-digitalizar-voo-radar-aviao-rota-caminho-com-scan-interface-hu (1) (1).jpg"))); // NOI18N
        jLabel2.setMinimumSize(new java.awt.Dimension(0, 0));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1000, 570);

        jMenuBar2.setBackground(new java.awt.Color(0, 153, 153));
        jMenuBar2.setForeground(new java.awt.Color(0, 0, 0));
        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAeronaveActionPerformed
        TabelaAeronave telaAeronave = new TabelaAeronave();
        telaAeronave.setVisible(true);
    }//GEN-LAST:event_botaoAeronaveActionPerformed

    private void botaoDesligarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDesligarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botaoDesligarActionPerformed

    private void botaoComandanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoComandanteActionPerformed
        TelaComandante telaComandante = new TelaComandante();
        telaComandante.setVisible(true);
    }//GEN-LAST:event_botaoComandanteActionPerformed

    private void botaoClimaTempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoClimaTempoActionPerformed
        TelaClimaTempo telaClima = new TelaClimaTempo();
        telaClima.setVisible(true);

    }//GEN-LAST:event_botaoClimaTempoActionPerformed

    private void txtMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMensagemActionPerformed
        TabelaEnviarMensagem tabelaEnviarMensagem = new TabelaEnviarMensagem();
        tabelaEnviarMensagem.setVisible(true);
    }//GEN-LAST:event_txtMensagemActionPerformed

    private void botaoSonoroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSonoroActionPerformed
        TelaAletar telaAlertar = new TelaAletar();
        telaAlertar.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSonoroActionPerformed

    private void botaoComandanteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoComandanteKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER);

    }//GEN-LAST:event_botaoComandanteKeyPressed

    private void botaoAeronaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoAeronaveKeyPressed

    }//GEN-LAST:event_botaoAeronaveKeyPressed

    private void botaoClimaTempoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoClimaTempoKeyPressed

    }//GEN-LAST:event_botaoClimaTempoKeyPressed

    private void txtMensagemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMensagemKeyPressed

    }//GEN-LAST:event_txtMensagemKeyPressed

    private void botaoSonoroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoSonoroKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSonoroKeyPressed

    private void botaoDesligarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoDesligarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDesligarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAeronave;
    private javax.swing.JButton botaoClimaTempo;
    private javax.swing.JButton botaoComandante;
    private javax.swing.JButton botaoDesligar;
    private javax.swing.JButton botaoSonoro;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JButton txtMensagem;
    // End of variables declaration//GEN-END:variables
}
