/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trafego.view;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import trafego.model.AeronaveDao;
import trafego.model.ClasseAeronave;
import trafego.model.ClasseLogin;
import trafego.model.ClasseLoginDao;
import trafego.model.ClasseMenu;

/**
 *
 * @author wesley
 */
public class TelaLogin extends javax.swing.JFrame {

    private final LoginController controller;

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        controller = new LoginController(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        lbUsuario = new javax.swing.JLabel();
        txtEntradaNome = new javax.swing.JTextField();
        botaoEntrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbSenha.setForeground(new java.awt.Color(255, 255, 255));
        lbSenha.setText("SENHA");
        getContentPane().add(lbSenha);
        lbSenha.setBounds(670, 420, 60, 20);

        txtSenha.setBackground(new java.awt.Color(0, 0, 0));
        txtSenha.setForeground(new java.awt.Color(255, 255, 255));
        txtSenha.setCaretColor(new java.awt.Color(255, 255, 255));
        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(txtSenha);
        txtSenha.setBounds(620, 450, 220, 30);

        lbUsuario.setBackground(new java.awt.Color(0, 0, 0));
        lbUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lbUsuario.setText("       USUÁRIO");
        getContentPane().add(lbUsuario);
        lbUsuario.setBounds(70, 430, 130, 20);

        txtEntradaNome.setBackground(new java.awt.Color(0, 0, 0));
        txtEntradaNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtEntradaNome.setForeground(new java.awt.Color(255, 255, 255));
        txtEntradaNome.setCaretColor(new java.awt.Color(255, 255, 255));
        txtEntradaNome.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtEntradaNome.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtEntradaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradaNomeActionPerformed(evt);
            }
        });
        txtEntradaNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEntradaNomeKeyPressed(evt);
            }
        });
        getContentPane().add(txtEntradaNome);
        txtEntradaNome.setBounds(30, 450, 240, 26);

        botaoEntrar.setBackground(new java.awt.Color(0, 0, 0));
        botaoEntrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoEntrar.setForeground(new java.awt.Color(255, 255, 255));
        botaoEntrar.setText("ENTRAR");
        botaoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarActionPerformed(evt);
            }
        });
        botaoEntrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoEntrarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                botaoEntrarKeyReleased(evt);
            }
        });
        getContentPane().add(botaoEntrar);
        botaoEntrar.setBounds(380, 500, 120, 50);

        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/F163D.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 580);

        setSize(new java.awt.Dimension(917, 581));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEntradaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradaNomeActionPerformed

    }//GEN-LAST:event_txtEntradaNomeActionPerformed

    private void botaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarActionPerformed
        String codigo;
        String codigo2;
        codigo = txtEntradaNome.getText();
        codigo2 = txtSenha.getText();
        ClasseLoginDao loginDao = new ClasseLoginDao();
        boolean status = loginDao.conectar();
        if (status == true) {
            ClasseLogin classeLogin = loginDao.consultar(codigo, codigo2);
            if (classeLogin == null) {
                JOptionPane.showConfirmDialog(null, "USUARIO OU SENHA INEXISTENTE.");
            } else {
                txtEntradaNome.setText(classeLogin.getUsuario());
                txtSenha.setText(classeLogin.getSenha());
                TelaMenu telaMenu = new TelaMenu();
                telaMenu.setVisible(true);
                this.dispose();
                telaMenu.setLocationRelativeTo(null);
                JOptionPane.showConfirmDialog(null, "LOGIN REALIZADO.");
            }
         

            loginDao.desconectar();
        } else {
            JOptionPane.showMessageDialog(null, "OPS!!!!FALHA NA CONEXÃO COM BANCO DE DADOS ");
        }

        
       
         

    }//GEN-LAST:event_botaoEntrarActionPerformed

    private void botaoEntrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoEntrarKeyPressed

        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            botaoEntrar.requestFocus();
        }
        TelaMenu telaMenu = new TelaMenu();
        telaMenu.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_botaoEntrarKeyPressed

    private void txtEntradaNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEntradaNomeKeyPressed

        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            txtSenha.requestFocus();
        }
    }//GEN-LAST:event_txtEntradaNomeKeyPressed

    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            botaoEntrar.requestFocus();
        }
    }//GEN-LAST:event_txtSenhaKeyPressed

    private void botaoEntrarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoEntrarKeyReleased
       
    }//GEN-LAST:event_botaoEntrarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JTextField txtEntradaNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

    private static class LoginController {

        private Object view;

        public LoginController(TelaLogin aThis) {
        }

        private void autenticar() {

            TelaMenu telaMenu = new TelaMenu();
            telaMenu.setVisible(true);
        }

    }

    public JTextField getTxtEntradaNome() {
        return txtEntradaNome;
    }

    public void setTxtEntradaNome(JTextField txtEntradaNome) {
        this.txtEntradaNome = txtEntradaNome;
    }

    public JPasswordField getTxtEntradaSenha() {
        return txtSenha;
    }

    public void setTxtEntradaSenha(JPasswordField txtEntradaSenha) {
        this.txtSenha = txtEntradaSenha;
    }

}
